language: node_js
node_js:
  - "stable"
dist: trusty
sudo: required
branches:
  only:
  - develop
cache:
  directories:
  - node_modules
script:
- npm run build
- cp CNAME public/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: develop