language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
branches:
  only:
  - develop
script:
- npm run build
- cp CNAME public/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: develop